services:
  - type: web
    name: bankmanager-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    buildCommand: docker build -t bankmanager-api .
    startCommand: docker/render-start.sh
    healthCheckPath: /api/v1/status
    healthCheckTimeout: 300
    envVars:
      - key: APP_NAME
        value: BankManager
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromSecret: db_host
      - key: DB_PORT
        fromSecret: db_port
      - key: DB_DATABASE
        fromSecret: db_database
      - key: DB_USERNAME
        fromSecret: db_username
      - key: DB_PASSWORD
        fromSecret: db_password
      - key: L5_SWAGGER_USE_ABSOLUTE_PATH
        value: true
      - key: MAIL_MAILER
        value: log
      - key: QUEUE_CONNECTION
        value: database
      - key: APP_URL
        fromService:
          type: web
          name: bankmanager-api
          property: host
      - key: L5_SWAGGER_BASE_PATH
        fromService:
          type: web
          name: bankmanager-api
          property: host
      - key: L5_SWAGGER_CONST_HOST
        fromService:
          type: web
          name: bankmanager-api
          property: host
